# Generated by Django 3.2.8 on 2021-11-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
