# Generated by Django 3.2.8 on 2021-11-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk', '0004_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
