# Generated by Django 3.2.8 on 2021-11-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk', '0005_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(),
        ),
    ]
