# Generated by Django 3.2.8 on 2021-11-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
