# Generated by Django 3.2.8 on 2021-11-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bk', '0008_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bk.source'),
        ),
    ]
