# Generated by Django 3.2.8 on 2021-11-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk', '0009_alter_income_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
