# Generated by Django 3.2.8 on 2021-11-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk', '0010_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(max_length=255),
        ),
    ]
