# Generated by Django 3.2.8 on 2021-11-08 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bk', '0011_alter_income_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relateds', to='bk.category'),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bk.source'),
        ),
    ]
